const scenariosData = [
    "In a cozy coffee shop with the aroma of freshly ground beans in the air",
    "At a bustling train station platform during rush hour",
    "Inside a quiet library with sunlight streaming through tall windows",
    "At a neighborhood grocery store's produce section",
    "In a modern gym during peak evening hours",
    "At a busy airport terminal near the departure gates",
    "In a local park on a sunny afternoon",
    "At a popular food truck during lunch hour",
    "Inside a vintage record store browsing vinyl collections",
    "At a pet shop looking at adorable puppies",
    "In a high-end restaurant during dinner service",
    "At a movie theater concession stand",
    "Inside a tech store checking out the latest gadgets",
    "At a bakery early in the morning",
    "In a hotel lobby during check-in time",
    "At a bus stop on a rainy morning",
    "Inside an art gallery during an exhibition",
    "At a farmers market on weekend morning",
    "In a dental office waiting room",
    "At a beachside ice cream stand",
    "Inside a shopping mall during a sale",
    "At a flower shop arranging bouquets",
    "In a doctor's office for a check-up",
    "At a car wash on a busy Saturday",
    "Inside a pizza parlor during dinner rush",
    "At a bank waiting in line",
    "In a yoga studio before class",
    "At a hair salon getting a haircut",
    "Inside a bookstore's reading corner",
    "At a post office mailing packages",
    "In a bowling alley on league night",
    "At an ice skating rink watching beginners",
    "Inside a music store testing instruments",
    "At a tailoring shop getting measurements",
    "In a dance studio during lessons",
    "At a bike shop looking for repairs",
    "Inside a candy store with endless choices",
    "At a sports bar during a big game",
    "In a photography studio during a session",
    "At a shoe store trying on new shoes",
    "Inside a comic book store on release day",
    "At a wedding dress boutique",
    "In a garden center picking plants",
    "At a language school reception",
    "Inside a sushi restaurant at the counter",
    "At a laundromat folding clothes",
    "In a computer repair shop",
    "At a jewelry store browsing rings",
    "Inside an arcade playing games",
    "At a camping store getting supplies"
];

const charactersData = [
    "A cheerful barista who's passionate about coffee art",
    "A friendly librarian who knows every book by heart",
    "A patient yoga instructor guiding new students",
    "A busy chef preparing special orders",
    "An enthusiastic tour guide sharing local history",
    "A knowledgeable wine sommelier at a fine restaurant",
    "A creative hairstylist discussing new trends",
    "A passionate music teacher giving lessons",
    "A helpful tech support specialist solving problems",
    "A caring veterinarian examining pets",
    "A skilled personal trainer motivating clients",
    "A detail-oriented tailor measuring for suits",
    "A professional photographer setting up shots",
    "A gentle dental hygienist explaining procedures",
    "A friendly bank teller processing transactions",
    "A enthusiastic dance instructor teaching steps",
    "A patient driving instructor giving tips",
    "A knowledgeable car mechanic explaining repairs",
    "A creative florist arranging bouquets",
    "A helpful hotel concierge giving recommendations",
    "A experienced flight attendant helping passengers",
    "A friendly bus driver greeting passengers",
    "A skilled bike mechanic fixing gears",
    "A passionate art gallery curator",
    "A helpful bookstore owner recommending books",
    "A professional real estate agent showing homes",
    "A friendly neighborhood mail carrier",
    "A skilled jeweler designing custom pieces",
    "A knowledgeable gardener sharing plant tips",
    "A patient language teacher explaining grammar",
    "A creative tattoo artist discussing designs",
    "A helpful pharmacy technician filling prescriptions",
    "A professional optometrist conducting eye exams",
    "A friendly movie theater usher",
    "A skilled shoe repair specialist",
    "A passionate comic book store owner",
    "A helpful travel agent planning trips",
    "A knowledgeable antique dealer",
    "A friendly ice cream vendor on the beach",
    "A professional dog trainer working with pets",
    "A creative cake decorator designing desserts",
    "A skilled massage therapist",
    "A helpful gym receptionist",
    "A passionate music store owner",
    "A friendly food truck operator",
    "A professional wedding planner",
    "A knowledgeable wine shop owner",
    "A helpful computer repair technician",
    "A friendly movie ticket seller",
    "A skilled skateboard shop owner"
];

// 随机匹配函数
function getRandomScenario() {
    const randomSceneIndex = Math.floor(Math.random() * scenariosData.length);
    const randomCharacterIndex = Math.floor(Math.random() * charactersData.length);
    
    return {
        scene: scenariosData[randomSceneIndex],
        character: charactersData[randomCharacterIndex]
    };
}
